version: '3.3'

networks:
  notification-network:
    driver: bridge

services:
  mongo:
    image: mongo:7.0-jammy
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=notification-service
    ports:
      - '27017:27017'
    networks:
      - notification-network

  mongo-express:
    image: mongo-express:1.0.0-18-alpine3.18
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
    ports:
      - '8081:8081'
    networks:
      - notification-network

  redis:
    image: 'redis:7.2.1-alpine'
    container_name: redis
    ports:
      - '6379:6379'
    networks:
      - notification-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - '8088:8081'
    depends_on:
      - redis
    networks:
      - notification-network
