version: '3.3'

networks:
  notification-network:
    driver: bridge

services:
  mongo:
    image: mongo:7.0-jammy
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=notification-service
    ports:
      - '27017:27017'
    networks:
      - notification-network
