version: '3.3'
services:
  db:
    restart: on-failure
    container_name: nest-boilerplate-pg
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=boilerplate
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - ./db:/var/lib/postgresql/data
      
  # redis:
  #   container_name: redis
  #   restart: on-failure
  #   image: redis
  #   ports:
  #   - '6379:6379'
  #   expose:
  #     - 6379
