version: '3.3'
services:
  app:
    restart: on-failure
    container_name: bloodbond
    image: high10hunter/node:latest
    ports:
      - '3000:3000'
    expose:
      - '3000'
    env_file:
      - .env
