POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "username": "kiemtran-test02",
  "password": "123"
}

###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "username": "kiemtran-dev",
  "password": "123"
}

###

POST http://localhost:5000/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzdiM2QxMTM2OTczNzY4NTFlMmZmMTUiLCJpYXQiOjE2NjkwMjUwOTZ9.MzMy1Ig0EUTbNLYX_W1rQK6qNmjfDYN9Am0zWUbn9og

{
  "title": "Node JS",
  "description": "Node + Express",
  "url": "nodejs.com",
  "status": "TO LEARN"
}

###

GET http://localhost:5000/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzdiM2QxMTM2OTczNzY4NTFlMmZmMTUiLCJpYXQiOjE2NjkwMjUwOTZ9.MzMy1Ig0EUTbNLYX_W1rQK6qNmjfDYN9Am0zWUbn9og

###

PUT http://localhost:5000/api/posts/637b4d5b4943ed6e6ea12f09
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzdiM2QxMTM2OTczNzY4NTFlMmZmMTUiLCJpYXQiOjE2NjkwMjUwOTZ9.MzMy1Ig0EUTbNLYX_W1rQK6qNmjfDYN9Am0zWUbn9og

{
  "title": "Angular",
  "description": "Angular",
  "url": "https://angular.org",
  "status": "LEARNING"
}

###

DELETE http://localhost:5000/api/posts/637b4cc52e1b346e301fcf44
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzdiM2QxMTM2OTczNzY4NTFlMmZmMTUiLCJpYXQiOjE2NjkwMjUwOTZ9.MzMy1Ig0EUTbNLYX_W1rQK6qNmjfDYN9Am0zWUbn9og